INSERT INTO COUNTRY (NAME) VALUES ('BRAZIL');
INSERT INTO STATE (NAME, COUNTRY_ID) VALUES ('SANTA CATARINA', 1);
INSERT INTO CITY (NAME, STATE_ID) VALUES ('JOINVILLE', 1);
INSERT INTO COMPANY (NAME, CITY_ID) VALUES ('NINTENDO', 1);
